# Hugo Resume Theme Parameters

firstName = "Athan"
lastName = "Dial, PhD"
address = "Boston, MA"
phone = "857-654-4798"
email = "athandial@gmail.com"
profileImage = "img/profile.jpg"
favicon = "/favicon.ico"
showQr = false
showContact = false

# Section ordering (top to bottom on page)
sections = ["skills", "tools", "experience", "education"]

# Social handles
[[handles]]
  name = "LinkedIn"
  link = "https://www.linkedin.com/in/athandial/"

[[handles]]
  name = "GitHub"
  link = "https://github.com/athan-dial"
